### ISSUE TITLE
Cyclical imports lead to elmLS crashing repeatedly

### ISSUE THREAD

**Issue by SiriusStarr** [elm-tooling/elm-language-server#145]
Should any modules in a project form a cyclical import, elmLS will repeatedly try to start up and immediately crash (until this has occurred 5 times in a row and it disables itself).

## Expected Behavior
Normal problem reporting, e.g.
```
-- IMPORT CYCLE ----------------------------------------------------------------

Your module imports form a cycle:

    ┌─────┐
    │    ModuleA
    │     ↓
    │    ModuleB
    └─────┘

Learn more about why this is disallowed and how to break cycles
here:<https://elm-lang.org/0.19.0/import-cycles>
```

## Current Behavior
Repeatedly crashes with message
```
TypeError: Cannot read property 'startsWith' of null
    at Function.getUriFromIssue (/home/user/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/server/out/providers/diagnostics/elmDiagnosticsHelper.js:27:24)
    at issues.reduce (/home/user/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/server/out/providers/diagnostics/elmDiagnosticsHelper.js:8:30)
    at Array.reduce (<anonymous>)
    at Function.issuesToDiagnosticMap (/home/user/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/server/out/providers/diagnostics/elmDiagnosticsHelper.js:7:23)
    at checkForErrors.then.issues (/home/user/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/server/out/providers/diagnostics/elmMakeDiagnostics.js:37:67)

/home/user/.vscode/extensions/elmtooling.elm-ls-vscode-0.4.2/server/node_modules/web-tree-sitter/tree-sitter.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readB
abort({}). Build with -s ASSERTIONS=1 for more info.
```

## Steps to Reproduce (for bugs)
1.  Create new elm folder
2.  Create file in `src` named `ModuleA.elm` with contents:
```elm
module ModuleA exposing (..)

import ModuleB


type alias PlaceholderA =
    Int
``` 
3.  Create file in `src` named `ModuleB.elm` with contents:
```elm
module ModuleB exposing (..)

import ModuleA


type alias PlaceholderB =
    Int
```
4.  Do anything to trigger elmLS (hover, save, etc.)

## Your Environment

* Version used: 
elmLS version: 0.4.2

Editor/OS info:

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.1.20-300.fc30.x86_64

**Comment by Razzeee** [comment]
This was released in the new version some minutes ago, going to close this.
