### ISSUE TITLE
language server fails with "Cannot find module"

### ISSUE THREAD

**Issue by akhilman** [elm-tooling/elm-language-server#176]
Language server with LanguageClient-neovim works about minute and then fails with:
```
/home/ildar/.config/yarn/global/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readBinary(e){var t=Module.read(e,!0);return t.buffer||(t=new Uint8Array(t)),assert(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),Module.arguments=proces

Error: Cannot find module '/home/ildar/Projects/learning-elm/first_steps/elm-stuff/packages/elm/html/1.0.0/elm.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.getDependencyFiles (/home/ildar/.config/yarn/global/node_modules/@elm-tooling/elm-language-server/node_modules/elm-analyse/dist/app/util/file-gatherer.js:63:26)
    at Array.<anonymous> (/home/ildar/.config/yarn/global/node_modules/@elm-tooling/elm-language-server/node_modules/elm-analyse/dist/app/ports/dependency-files.js:13:35)
    at Function.f (/home/ildar/.config/yarn/global/node_modules/@elm-tooling/elm-language-server/node_modules/elm-analyse/dist/app/backend-elm.js:2170:19)
    at A3 (/home/ildar/.config/yarn/global/node_modules/@elm-tooling/elm-language-server/node_modules/elm-analyse/dist/app/backend-elm.js:59:28)
    at Object.b (/home/ildar/.config/yarn/global/node_modules/@elm-tooling/elm-language-server/node_modules/elm-analyse/dist/app/backend-elm.js:1974:7)
    at _Scheduler_step (/home/ildar/.config/yarn/global/node_modules/@elm-tooling/elm-language-server/node_modules/elm-analyse/dist/app/backend-elm.js:1818:20)
```

## Steps to Reproduce (for bugs)

1. Start nvim with LanbuageClient and elm-language-server.
2. Write some code.
3. LanguageClent prints error "sending on disconnected channel".

## Context
I try to do tutorial from https://guide.elm-lang.org/architecture/buttons.html

## Your Environment
* Version used: @elm-tooling/elm-language-server@1.4.1 installed globally with yarn
* Editor used: nvim-0.3.8 with up to date LanguageClient-neovim
* Environment name and version: node v10.16.3
* Operating System and version: Debian LInux Sid up to date.

**Comment by akhilman** [comment]
Closing because this is a error in elm-analyse.
