### ISSUE TITLE
Updated to 1.12.0 and elm-language-server can't start

### ISSUE THREAD

**Issue by romariolopezc** [elm-tooling/elm-language-server#333]
I just updated to the latest version to try it but it can't start. `:CocInfo` shows the problems.

## Expected Behavior

I didn't change anything, just updated the package

## Current Behavior

Elm language server crashing
```
[Info  - 8:11:43 PM] Done parsing all files for /home/rlopez/repos/elm/project/elm.json
TypeError: allTopLevelFunctions.filter(...).map(...).filter(...).flatMap is not a function
/home/rlopez/.config/yarn/global/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);var r,n,s=[],o=function(e,t){throw t},_=!1,a=!1;_="object"==typeof window,a="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n=!_&&!r&&!a;var i,u,l,d,c="";r?(c=a?require("path").dirname(c)+"/":__dirname+"/",i=function(e,t){return l||(l=require("fs")),d||(d=require("path")),e=d.normalize(e),l.readFileSync(e,t?null:"utf8")},u=function(e){var t=i(e,!0);return t.buffer||(t=new Uint8Array(t)),L(t.buffer),t},process.argv.length>1&&process.argv[1].replace(/\\/g,"/"),s=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=Module),process.on("uncaughtException",function(e){if(!(e instanceof Ue)

RuntimeError: abort(TypeError: allTopLevelFunctions.filter(...).map(...).filter(...).flatMap is not a function). Build with -s ASSERTIONS=1 for more info.
    at process.fe (/home/rlopez/.config/yarn/global/node_modules/web-tree-sitter/tree-sitter.js:1:10450)
    at process.emit (events.js:203:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
[Info  - 8:11:43 PM] Connection to server got closed. Server will restart.
[Error  - 8:11:43 PM] elm-language-server exited with code: 7
[Info  - 8:11:43 PM] Loading Elm tree-sitter syntax from ../../../.config/yarn/global/node_modules/@elm-tooling/elm-language-server/out/tree-sitter-elm.wasm
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.12.0
* Editor used: neovim
* Environment name and version (e.g. node.js 5.4): 10.17.0
* Operating System and version: `Linux xps 5.4.69-1-lts #1 SMP Thu, 01 Oct 2020 20:40:59 +0000 x86_64 GNU/Linux`

**Comment by Razzeee** [comment]
Pushed a new version, so this should hopefully fix this.

**Comment by romariolopezc** [comment]
Seems fixed, thanks and very good update!
