### ISSUE TITLE
LS cannot find packages when using Docker

### ISSUE THREAD

**Issue by sporto** [elm-tooling/elm-language-server#457]
Upon opening an Elm file with v2 of the language server I get:

`The Elm server crashed 5 times in the last 3 minutes. The server will not be restarted.`

The last part of the output is

```
TypeError: Cannot read property 'synchronize' of undefined
/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);var r,n,s=[],o=function(e,t){throw t},_=!1,a=!1;_="object"==typeof window,a="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n=!_&&!r&&!a;var i,u,l,d,c="";r?(c=a?require("path").dirname(c)+"/":__dirname+"/",i=function(e,t){return l||(l=require("fs")),d||(d=require("path")),e=d.normalize(e),l.readFileSync(e,t?null:"utf8")},u=function(e){var t=i(e,!0);return t.buffer||(t=new Uint8Array(t)),L(t.buffer),t},process.argv.length>1&&process.argv[1].replace(/\\/g,"/"),s=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=Module),process.on("uncaughtExce

RuntimeError: abort(TypeError: Cannot read property 'synchronize' of undefined). Build with -s ASSERTIONS=1 for more info.
    at process.fe (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/server/node_modules/web-tree-sitter/tree-sitter.js:1:10450)
    at process.emit (events.js:228:7)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
[Error - 11:59:53 am] Connection to server got closed. Server will not be restarted.
[Error - 11:59:53 am] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at ChildProcess.<anonymous> (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 11:59:53 am] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at IPCMessageReader.fireClose (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at ChildProcess.<anonymous> (/home/sebastian/.vscode/extensions/elmtooling.elm-ls-vscode-2.0.0/client/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```

The whole output is here https://gist.github.com/sporto/9a35f5caa1184807ea9d12412fcadac7

## Current Behavior
Language server crashes

## Steps to Reproduce (for bugs)
1. Install language server v2
2. Open an Elm file

## Your Environment
* VScode 1.52.1
* Node 14.15.1
* Linux pop-os 20.10

**Comment by Razzeee** [comment]
Can you check if `/home/sebastian/.elm/0.19.1/packages/NoRedInk/elm-json-decode-pipeline/1.0.0/elm.json` exists? Or a similar entry in elm-stuff?

**Comment by sporto** [comment]
@Razzeee Docker is the issue!
I checked the path that you said and I didn't have that package there.
We use Docker for development, so `elm make` doesn't install packages there.
Then I run `elm make` outside of Docker and the crash went away.

**Comment by Razzeee** [comment]
Do you know where elm make is putting them instead, do we fail reading your elm home env?

**Comment by sporto** [comment]
It puts the cached packages in `/root/.elm`
But only when installing.
After I exit and enter the container again, that directory is gone (as is not persisted anywhere). But `elm make` works fine.

I will need to experiment with Docker volumes to point `/root/.elm` inside Docker to my home folder (`/home/sebastian/.elm`)

**Comment by sporto** [comment]
With docker compose doing this fixes the issue:

```
client:
    ...
    volumes:
      ...
      - ~/.elm:/root/.elm
````

Then Elm will put packages on the host and the language server works.

I'm not sure if the LS can do anything about this. Maybe just document this issue.

**Comment by emilgoldsmith** [comment]
@sporto and anyone else you can also see the alternative solution (though not with compose but could surely be adapted to it) I made in the PR to the default dev container here microsoft/vscode-dev-containers#729.

I believe that the solution you suggested should work whenever you already have a ~/.elm folder created locally, which is probably pretty often if you're an elm dev, but it would fail if it doesn't exist to my knowledge. The above solution should work "out of the box"

**Comment by Razzeee** [comment]
I'm going to close this then. Feel free to ping, if this should be opened up again.
