### ISSUE TITLE
Changing type def causes error

### ISSUE THREAD

**Issue by romariolopezc** [elm-tooling/elm-language-server#92]
I changed from `Model` to `String` and this error popped out in `:CocInfo`

```sh
[Info  - 11:35:15 AM] Connection to server got closed. Server will restart.                      
 [Error  - 11:35:15 AM] Request textDocument/completion failed.                                                                                                                            
 Error: Connection got disposed.                                                                  
     at Object.dispose (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:38066:25)                                                                                        
     at Object.dispose (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:64562:35)                            
     at LanguageClient.handleConnectionClosed (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:66682:42)                                                                  
     at LanguageClient.handleConnectionClosed (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:64199:15)      
     at closeHandler (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:66668:18)                                                                                              
     at CallbackList.invoke (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:38708:39)                                                                                      
     at Emitter.fire (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:38766:36)          
     at closeHandler (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:37416:26)                                                                                              
     at CallbackList.invoke (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:38708:39)                                                                                        
     at Emitter.fire (/home/rlopez/.local/share/nvim/plugged/coc.nvim/build/index.js:38766:36)                                                                                            
 [Error  - 11:35:15 AM] elm-language-server exited with code: null
```

**Comment by Razzeee** [comment]
Please be more specific. What exactly did you change?

**Comment by romariolopezc** [comment]
I changed this
`update : Msg -> Model -> (Model, Cmd Msg)`
to
`update : Msg -> String -> (Model, Cmd Msg)`

And the error popped, in fact just working with the file fails unexpectedly, editing or adding code pops failures :(

**Comment by Razzeee** [comment]
Does this still happen? Your using coc with neovim?

**Comment by Razzeee** [comment]
Closing due to no feedback
